Documentation 📚
Ale32bit/SwitchChat pull request #9
Opened 2023-03-15 16:07 UTC by piprett

I have made some documentation. It is in no way perfect, and I am in no way good at English. Please do nitpick.
Fixes #7.
I used obsidian.md while writing this, so my markdown may be a bit off.

2023-03-15 20:04 UTC, Ale32bit approved these changes

2023-03-15 20:04 UTC, Ale32bit commented on README.md
> -[![npm version](https://badge.fury.io/js/switchchat.svg)](https://www.npmjs.org/package/switchchat)
Any reason behind removing the npm version badge?

2023-03-15 20:05 UTC, piprett commented on README.md
> -[![npm version](https://badge.fury.io/js/switchchat.svg)](https://www.npmjs.org/package/switchchat)
![image](https://user-images.githubusercontent.com/49862976/225429653-728eb7d0-0b87-4ba8-a456-7f5db76b6538.png)
Sorry? I can't see this

2023-03-15 21:15 UTC, Lemmmy requested changes
Thank you for your work on this! My review leaves a lot of small nitpicks/nags, mostly regarding formatting, grammar, and consistency with [docs.sc3.io](https://docs.sc3.io/chatbox/websocket.html). I will probably do another pass over this after it is merged, but what you have here is a fantastic start.

When #11 is merged and deployed, I will also add links between the various places of documentation (README, sc-docs, etc.), but don't worry about that in your PR.

2023-03-15 21:15 UTC, Lemmmy commented on README.md
> +- text - `String` of the contents of the chat message
JavaScript primitives are written in lowercase, so this should be `string` (and in all other instances of this)

2023-03-15 21:15 UTC, Lemmmy commented on README.md
> +  if (cmd.command == 'helloworld') {
Use [triple equals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Strict_equality) here (`===`)

```suggestion
  if (cmd.command === 'helloworld') {
```

2023-03-15 21:15 UTC, Lemmmy commented on README.md
> +- user - `User` that goes AFK
```suggestion
### AFK return

- user - `User` that went AFK
```

2023-03-15 21:15 UTC, Lemmmy commented on README.md
> +| Restart cancelled | server_restart_cancelled | When a restart gets cancelled                |
```suggestion
| Friendly name     | Name                     | Trigger                                    |
| ----------------- | ------------------------ | ------------------------------------------ |
| AFK               | afk                      | A player went AFK                          |
| AFK return        | afk_return               | A player returned from being AFK           |
| In-game chat      | chat_ingame              | A player sent a message in-game            |
| Discord chat      | chat_discord             | A player sent a message from Discord       |
| Chatbox message   | chat_chatbox             | A chatbox sent a public message            |
| Chatbox command   | command                  | A player sent a chatbox command in-game    |
| Death             | death                    | A player died                              |
| Join              | join                     | A player joined the server                 |
| Disconnect        | leave                    | A player left the server                   |
| Restart scheduled | server_restart_scheduled | The server will restart soon               |
| Restart cancelled | server_restart_cancelled | The scheduled server restart was cancelled |
```

2023-03-15 21:15 UTC, Lemmmy commented on README.md
> +- source - `User` | `null` that killed the user. Only sent if they was killed by a player
```suggestion
- source - `User` | `null` that killed the user. Only set if they were killed by another player
```

2023-03-15 21:15 UTC, Lemmmy commented on README.md
> +- rawText - Raw `string` of the death message
```suggestion
- text - `string` of the death message contents, without formatting codes
- rawText - `string` of the death message contents, with its original formatting codes
```

2023-03-15 21:15 UTC, Lemmmy commented on README.md
> +- rawName - Raw `string` name of the chatbox that broadcasted
```suggestion
### Chatbox message

- text - `string` of the contents of the message, without formatting codes
- rawText - `string` of the raw contents of the message, with its original formatting codes
- renderedText - `RenderedTextObject` of the rendered text of the message
- user - `User` of the owner of the chatbox
- name - `string` name of the chatbox, without formatting codes
- rawName - `string` name of the chatbox, with its original formatting codes
```

2023-03-15 21:15 UTC, Lemmmy commented on README.md
> +- edited - `Boolean` if the message has been edited
```suggestion
### Discord chat

- text - `string` of the contents of the chat message, without formatting codes
- rawText - `string` of the raw contents of the chat message, with its original formatting codes
- renderedText - `RenderedTextObject` of the rendered text of the chat message
- discordId - `string` of the Discord snowflake ID of the message
- discordUser - `DiscordUser` that sent the message
- edited - `boolean` if the message has been edited
```

2023-03-15 21:15 UTC, Lemmmy commented on README.md
> +- ownerOnly - `Boolean` that says if this command was visible to everyone's chatbox, or only the owner
```suggestion
### Chatbox command

- user - `User` that sent the chatbox command
- command - The first part of the command they sent. Eg. \\**command** arg1 arg2
- args - Array of `string`s that contain the args that come after the command
- ownerOnly - `boolean` if the command is an owner-only command (`^command`)
```

2023-03-15 21:15 UTC, Lemmmy commented on README.md
> +Not fully implemented
Heads-up: with #11 these are implemented

2023-03-15 21:15 UTC, Lemmmy commented on README.md
> +| Playerlist packet | players | When you connect, and when a player joines/leaves         |
```suggestion
| Friendly name     | Name    | Trigger                                                   |
| ----------------- | ------- | --------------------------------------------------------- |
| Hello packet      | ready   | When SwitchChat has successfully connected to SwitchCraft |
| Playerlist packet | players | When you connect, and when a player joins/leaves          |
```

2023-03-15 21:15 UTC, Lemmmy commented on README.md
> +- closeReason - `String` reson for closing the connection. You can find possible values at the [SwitchCraft wiki](https://docs.sc3.io/chatbox/websocket.html#closing-packet)
```suggestion
- error - `String` that tells you what type of error that occoured. You can find possible errors at the [SwitchCraft documentation](https://docs.sc3.io/chatbox/websocket.html#error-packet).
- text - `String` that is a human readable version of `error`.

### Closing packet

- closeReason - `String` reson for closing the connection. You can find possible values at the [SwitchCraft documentation](https://docs.sc3.io/chatbox/websocket.html#closing-packet).
```

2023-03-15 21:15 UTC, Lemmmy commented on README.md
> +- discriminator - The four numbers that identify this user from all the other with the same name
```suggestion
- id - The Discord snowflake ID of the user
- name - The Discord name of the user
- displayName - The user's server nickname on Discord, or their username if it is not set
- discriminator - The user's discriminator on Discord
```

2023-03-15 21:15 UTC, Lemmmy commented on README.md
> +Weird JSON object that minecraft uses for rendering.
```suggestion
Minecraft's serialised [raw JSON text format](https://minecraft.fandom.com/wiki/Raw_JSON_text_format). See the [SwitchCraft documentation](https://docs.sc3.io/chatbox/websocket.html#raw-json-text-object) for more information on how this is used.
```

2023-03-15 21:15 UTC, Lemmmy commented on README.md
> +- format - To use minecraft formatting for outgoing chatbox messages
```suggestion
The mode to use for outgoing chatbox messages (`.say()`, `.tell()`). 

- markdown - Discord-like [Markdown syntax](https://support.discord.com/hc/en-us/articles/210298617-Markdown-Text-101-Chat-Formatting-Bold-Italic-Underline-). Supports URLs, but not colours.
- format - Minecraft-like [formatting codes](https://minecraft.fandom.com/wiki/Formatting_codes) using ampersands (e.g. `&e` for yellow). Supports colours, but not URLs.
```

2023-03-15 21:42 UTC, Lemmmy commented
As outlined in #11, I have created a stub page for documentation at [docs.sc3.io](https://docs.sc3.io/chatbox/switchchat.html) which we can work on after this PR is merged. The tsdocs are also available [online](https://docs.sc3.io/library/switchchat/).

2023-03-16 13:37 UTC, piprett commented on README.md
> +Not fully implemented
Would you like me to document the code changes in #11, or will you take care of this?

2023-03-16 15:23 UTC, Lemmmy commented on README.md
> +Not fully implemented
I can take care of it if you prefer.

2023-03-16 16:36 UTC, Lemmmy approved these changes
LGTM, thanks for your work on this!

2023-03-16 16:37 UTC, merged